# Generated by Django 2.0.3 on 2018-04-05 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(0, 60)),
        ),
    ]
